// Copyright 2026 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono2
//    unicode_glyphs | a1&F↕@#ä
//    output         | fonts
//    input          | unifont_80.png

#pragma once

#include <qp.h>

extern const uint32_t font_unifont_80_length;
extern const uint8_t  font_unifont_80[2187];
